### ISSUE TITLE
Add better explanations to custom exceptions

### ISSUE THREAD

**Issue by jjzazuet** [vaccovecrana/metolithe#30]
FFS...

```
io.vacco.metolithe.core.MtException$MtForeignKeyMismatchException
	at io.vacco.metolithe.codegen.liquibase.MtLb.mapForeignKey(MtLb.java:102)
	at io.vacco.metolithe.codegen.liquibase.MtLb.lambda$mapForeignKeys$4(MtLb.java:126)
	at io.vacco.metolithe.codegen.liquibase.MtLb.mapForeignKeys(MtLb.java:128)
	at io.vacco.metolithe.codegen.liquibase.MtLb.lambda$build$20(MtLb.java:181)
```

Yes... but which entities?

**Comment by jjzazuet** [comment]
Improved badForeignKey message with entity context + updated test. Closes #30
